### ISSUE TITLE
建议用中文

### ISSUE THREAD

**Issue by fumiama** [FloatTech/.github#1]
外国人基本不用 `qq` (

**Comment by fumiama** [comment]
另外，无需写出主要仓库，因为主页有`pinned`。当然，pinned 中没有的可以适当做介绍，因为`pinned`只有6个位置。

**Comment by StarxSky** [comment]
好哒~，不过用英文显得高尚点[/doge]

**Comment by fumiama** [comment]
没必要，增加阅读难度。而且英文写的不 native 反而会被笑话。
