### ISSUE TITLE
有关FloatTech组织的主页介绍处组织标识图片收集

### ISSUE THREAD

**Issue by StarxSky** [FloatTech/.github#2]
收集具有象征Floattech的图标将会在组织的主页进行展示，可以自由发挥尺寸要与主页的README.md大小合适！！
可以参考微软的页面https://github.com/microsoft
欢迎大家制作
图标内容：
1.具有突出Floattech的特点

**Comment by fumiama** [comment]
atri

**Comment by StarxSky** [comment]
@fumiama 已采用谢谢！！
